# Generated by Django 4.2.3 on 2023-08-31 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='maxScore',
            new_name='Shushoku_maxScore',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='previousScore',
            new_name='Shushoku_previousScore',
        ),
    ]
