# Generated by Django 4.2.3 on 2023-10-05 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0002_rename_maxscore_userinformation_shushoku_maxscore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
