# Generated by Django 4.2.3 on 2023-10-28 05:45

from django.db import migrations, models
import interview.models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_alter_userinformation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=interview.models.dir_path_name),
        ),
    ]
