# Generated by Django 4.2.3 on 2023-12-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_userinformation_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='Shushoku_maxScore',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='Shushoku_previousScore',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='advise',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
